# Jim's Emacs Configuration

* Dvorak Tweaks

** Swap C-x and C-t

On a Dvorak keyboard, ~C-x~ is a stretch. Literally.
Globally replace ~C-x~ with ~C-t~ (and vice-versa).

#+begin_src emacs-lisp
(keyboard-translate ?\C-t ?\C-x)
(keyboard-translate ?\C-x ?\C-t)
#+end_src

** Enable Hack font

Enable the [[https://sourcefoundry.org/hack/][Hack font]], ignoring any errors that occur (e.g. if font cannot be found).

# To install Hack on Debian:
# sudo apt install fonts-hack

#+begin_src emacs-lisp
  (ignore-errors
    (set-face-attribute 'default nil :family "Hack" :height 146))
#+end_src

A word on coding with beautiful fonts:

Beautifully designed fonts look amazing at high resolution. If you
drop the resolution -- if you're trying to max out the number of
characters on your screen, for example -- you can lose a lot of
that beauty.

I went with the Hack font because, as the font designers point out:
> The regular weight is comfortable to read at the
> small text sizes used for source code development.

Sure enough, at height 146 -- the size needed to fit two 80-character
windows side-by-side on my System76 Lemur Pro 10 laptop -- the font
still holds up.

** Enable fallback font for Unicode ranges

To install Noto Color
# sudo apt install fonts-noto-color-emoji

#+begin_src emacs-lisp
;; Emoji fallback
(set-fontset-font t 'emoji "Noto Color Emoji" nil 'prepend)
#+end_src

** Configure Printer

Configure basic [[https://www.gnu.org/software/emacs/manual/html_node/emacs/Printing.html][printing settings]].

#+begin_src emacs-lisp
  (setq lpr-command "lp")
  ; The lp command can run without switches
  ; (and fails when default switches are used)
  (setq lpr-add-switches nil)
#+end_src

* Habitica

Install [[https://github.com/abrochard/emacs-habitica][emacs-habitica]].

#+begin_src emacs-lisp
  (message "load habitica")
  (use-package habitica
    :ensure t
    :config
    (setq habitica-uid "123")
    (setq habitica-token "456"))
#+end_src
